### ISSUE TITLE
Implement a API key check into the config

### ISSUE THREAD

**Issue by grumpyp** [grumpyp/aixplora#123]
As of now people use expired keys or are not paying for the API.

```
The issue is that ChatGPT API is not included inside ChatGPT Plus: "Please note that the ChatGPT API is not included in the ChatGPT Plus subscription and are billed separately. The API has its own [pricing](https://openai.com/pricing) [...]. The ChatGPT Plus subscription covers usage on chat.openai.com only and costs $20/month."
```

So we need to implement a check which verboses this. Otherwise error handling is not easy. Reference:

https://stackoverflow.com/questions/76522693/how-to-check-the-validity-of-the-openai-key-from-python

**Comment by omkar806** [comment]
Can you explain which more errors users can face using expired api keys so those exceptions can be handled

**Comment by grumpyp** [comment]
Rate Limit, Invalid Key,.. Might check here:

https://github.com/openai/openai-python/blob/main/openai/tests/test_exceptions.py

Do you want to work on it?

**Comment by NikoRaisanen** [comment]
Hey @grumpyp I just saw this issue, mind if I give it a shot?

**Comment by grumpyp** [comment]
hey @NikoRaisanen saw you gave it a shot! I will do the review today.

**Comment by NikoRaisanen** [comment]
Woops, I should have included a link to the issue in the PR.
I think we can close out this issue now: https://github.com/grumpyp/aixplora/commit/58fd9dda2963abbb4a4bd02603f5d14e0f2bf29e

**Comment by grumpyp** [comment]
@NikoRaisanen thanks for the reminder and your work! Closed
