### ISSUE TITLE
[BUG] : Horizontal bar appearing on smaller screen

### ISSUE THREAD

**Issue by md-abid-hussain** [grumpyp/aixplora#133]
The landing page of aixplora is unresponsive at few places.
![Screenshot (10)](https://github.com/grumpyp/aixplora/assets/101964499/09e8e900-e9dc-4b75-b385-546631ad3b53)

I would like to work on this issue as well

**Comment by grumpyp** [comment]
sure, awesome!

Feel free to improve it :)

**Comment by grumpyp** [comment]
any progress on that one? @md-abid-hussain

**Comment by md-abid-hussain** [comment]
I'm really sorry I have not done anything yet. 
If there is anyone who can fix it quick please assign it to them otherwise i will fix it by tomorrow.

**Comment by grumpyp** [comment]
Awesome. Tomorrow is totally fine ;)

**Comment by grumpyp** [comment]
ping

**Comment by md-abid-hussain** [comment]
I'm working on it.
