### ISSUE TITLE
Customizable OpenAI API  / proxy

### ISSUE THREAD

**Issue by FelisDwan** [grumpyp/aixplora#134]
Could you consider adding support for customizing OpenAI API or proxy address? This would make it easier to integrate some custom LLMs.
Thanks a lot.

**Comment by grumpyp** [comment]
Hi there,

would you like to integrate it? Can you share examples, maybe someone would like to implement it.

I am busy with some other tasks and not located in my homebase atm.

**Comment by FelisDwan** [comment]
Close issue.

**Comment by FelisDwan** [comment]
Close issue
