### ISSUE TITLE
Add .ppt loader

### ISSUE THREAD

**Issue by grumpyp** [grumpyp/aixplora#2]
Similar to the pdf_loader, a good start would be a loader for powerpoint files.

https://github.com/grumpyp/aixplora/blob/main/backend/loaders/pdf_loader.py

**Comment by TarunRKaushik** [comment]
hey could I please pick this issue?

**Comment by TarunRKaushik** [comment]
https://github.com/grumpyp/aixplora/pull/4
please review whenever free

**Comment by grumpyp** [comment]
Hi @TarunRKaushik, done.

Please do some small fixes and it can be merged 🚀

**Comment by TarunRKaushik** [comment]
can we close this issue? I think it was closed
