### ISSUE TITLE
Unable to install on windows machine

### ISSUE THREAD

**Issue by TarunRKaushik** [grumpyp/aixplora#28]
Seeing the below error when trying to `pip install -r backend/requirements.txt`
"RuntimeError: uvloop does not support Windows at the moment".

**Comment by grumpyp** [comment]
Can you see if it works if you delete the `uvloop` from the `requirements.txt`? You said you've got a workaround already in the PR, would you share it?

**Comment by TarunRKaushik** [comment]
not really a workaround, I just tested the pr changes by calling the load_presentation() in main.py and checking the contents of the file generated if it had the words from the pptx

**Comment by TarunRKaushik** [comment]
Also removing it from the requirements.txt doesn't work. Starts throwing this error:
`C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.33.31629\include\yvals.h(12): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory`

Adding the windows support issue from uvloop for visibility
https://github.com/MagicStack/uvloop/issues/14

**Comment by dipta10** [comment]
- I'm using Windows and I also ran into the same issue. My workaround was to use WSL2 for the backend.
- Also, I faced some issues while installing the frontend in WSL2. So I had to install the frontend in Windows.
- Also for some reason running `npm install frontend` from the project root directory fails, I had to run `npm install` from `/frontned`

**Comment by grumpyp** [comment]
Would you guys want to add this stuff to the README? Would be super helpful and for now a good way to make it work for Windows users. 

Basically also a part of #26

**Comment by grumpyp** [comment]
We have a workaround with docker now. Implemented in #62
