### ISSUE TITLE
Cannot run frontend

### ISSUE THREAD

**Issue by ruze00** [grumpyp/aixplora#30]
npm start from a clean install on WSL:

TypeError
Cannot read properties of undefined (reading 'ipcRenderer')
Call Stack
 ./src/renderer/index.tsx
  renderer.dev.js:66999:17
 options.factory
  renderer.dev.js:78064:31
 __webpack_require__
  renderer.dev.js:77510:33
 undefined
  renderer.dev.js:78649:37
 undefined
  renderer.dev.js:78652:12
 webpackUniversalModuleDefinition
  renderer.dev.js:7:11
 undefined
  renderer.dev.js:10:3

**Comment by ruze00** [comment]
Actually it might be the result from an error in the backend:

sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file

**Comment by dipta10** [comment]
> Actually it might be the result from an error in the backend:
> 
> sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file

Did you run the file from the project directory like `python backend/main.py` or within the backend directory like `python main.py`

**Comment by ruze00** [comment]
I ran it from within the `backend` directory.

Running it again just now with `python backend/main.py` stopped the backend from erroring but the frontend error is the same.

**Comment by grumpyp** [comment]
Share some information about your setup and machine please

**Comment by ruze00** [comment]
I'm using WSL from a scratch install.  Nothing other than following the directions on the README page, except for the frontend which will not run as written but rather needs a `cd frontend` and then `npm start` as per another user's feedback.

**Comment by grumpyp** [comment]
Hi @ruze00 can you checkout that PR and see if it works for you?
https://github.com/grumpyp/aixplora/pull/76

**Comment by grumpyp** [comment]
we have a version which works with docker now. It's just a "workaround" but as of now a way to enable everyone. More information in #62
