### ISSUE TITLE
create docker environment for devs

### ISSUE THREAD

**Issue by grumpyp** [grumpyp/aixplora#42]
right now people on windows have issues to setup the project #28 #30

Docker would be the way to go for now

**Comment by TarunRKaushik** [comment]
could you assign this to me? I'd like to have a shot at this.

**Comment by grumpyp** [comment]
> could you assign this to me? I'd like to have a shot at this.

sure! thank you. If you need assistance, hit me up on Discord :)

**Comment by grumpyp** [comment]
done in #62
