### ISSUE TITLE
toggle between dark and light theme

### ISSUE THREAD

**Issue by duckduckcodes** [grumpyp/aixplora#53]
add ability to toggle between light and dark theme, the theme icon should be in the navbar, (Menu.tsx)

**Comment by samahrens** [comment]
Can I have this issue?

**Comment by grumpyp** [comment]
Hi @samahrens yes, please go ahead. I assign you to the ticket.

Please use https://mantine.dev/, it should be straight forward.

Thanks!

**Comment by samahrens** [comment]
Hi @grumpyp where in the navbar do you want the dark/light mode button to be placed?

**Comment by grumpyp** [comment]
Hi,

at this point it doesn't really matter as long as it's a simple component you build. Maybe the `Footer`, what do you think?

**Comment by samahrens** [comment]
Yeah, anywhere is good. I'll put it in the Footer for now.

**Comment by grumpyp** [comment]
perfectly done! THX :)

done in #84
