### ISSUE TITLE
sqlalchemy.exc.OperationalError whenever I run main.py from inside the /backend/ directory

### ISSUE THREAD

**Issue by Blankscreen-exe** [grumpyp/aixplora#92]
Since sqlite is using the relative URL (_with 3 slashes after colon_) `SQLITE_DATABASE_URL = "sqlite:///backend/database/aixplora.db"` as declared inside `backend\database\database.py`. running the `main.py` while inside `/backend/` directory is causing an `sqlalchemy.exc.OperationalError`. A sample log of this error is given below:

```shell
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: https://sqlalche.me/e/20/e3q8)
```
and suggested by the URL given in the log, the problem is not with `sqlalchemy`.

>The `OperationalError` is the most common (but not the only) error class used by drivers in the context of the database connection being dropped, or not being able to connect to the database. For tips on how to deal with this, see the section [Dealing with Disconnects](https://docs.sqlalchemy.org/en/20/core/pooling.html#pool-disconnects).

I overcame this by running
```shell
# ./aixplora

python3 ./backend/main.py
```
instead of
```shell
# ./aixplora/backend

python3 ./main.py
```

I'm not sure if this is a big threat right now but it should be solved via `os` and `os.path` module in the future.

**Comment by grumpyp** [comment]
Hi, by running `python3 backend/main.py` there shouldn't be any error?

**Comment by Blankscreen-exe** [comment]
Yes that's what I encountered

**Comment by grumpyp** [comment]
The README says run it via `python3 backend/main.py` it should be clear. If you want to refactor it, I am happy to merge your PR!
