### ISSUE TITLE
README: Setup

### ISSUE THREAD

**Issue by djibe** [grumpyp/aixplora#93]
Readme commands don't work with NodeJS 18. Replace

```
pip install -r backend/requirements.txt
npm install frontend
```

with

```
pip install -r backend/requirements.txt
cd frontend
npm install
cd ..
```

and `python backend/main.py` with `python3 backend/main.py`

**Comment by grumpyp** [comment]
Hi there, I am not sure about that.

I believe, especially for the `python3` it is just an alias. Havn't heard any other problems about that. I will leave the issue open and we will see if someone thumb's up or something on it.

Thanks for reporting!
